const branches=[{name:'Zürich Nord',forecast:1840,pph:23.5,hours:8,ppv:148,absence:5.2,staff:12},{name:'Bern',forecast:1420,pph:22.8,hours:8,ppv:142,absence:6.1,staff:10},{name:'Basel',forecast:1280,pph:24.1,hours:8,ppv:151,absence:4.4,staff:9},{name:'Luzern',forecast:980,pph:21.9,hours:8,ppv:139,absence:7.2,staff:7}];
const days=['Mo, 16. Sep','Di, 17. Sep','Mi, 18. Sep','Do, 19. Sep','Fr, 20. Sep','Sa, 21. Sep'];const volumes=[4890,5120,5310,4980,5480,3910],available=[143,148,150,146,151,110];
const need=b=>Math.ceil((b.forecast/b.pph/b.hours)/(1-b.absence/100-Number(localStorage.holiday||10)/100));const vehicles=b=>Math.ceil(b.forecast/b.ppv);
function render(){document.querySelector('#staffKpi').innerHTML=`${branches.reduce((s,b)=>s+need(b),0)} <small>FTE</small>`;document.querySelector('#vehicleKpi').innerHTML=`${branches.reduce((s,b)=>s+vehicles(b),0)} <small>Fahrzeuge</small>`;
document.querySelector('#branchList').innerHTML=branches.map(b=>{let pct=Math.min(100,Math.round(b.staff/need(b)*100));return `<div class="branch"><span><b>${b.name}</b><br><small>${b.staff} / ${need(b)} FTE</small></span><div class="progress"><i style="width:${pct}%"></i></div><b>${pct}%</b></div>`}).join('');
document.querySelector('#chart').innerHTML=days.map((d,i)=>{let n=Math.round(volumes[i]/35);return `<div class="barset"><i class="bar need" style="height:${n/1.7}%"></i><i class="bar available" style="height:${available[i]/1.7}%"></i><label>${d.slice(0,2)}</label></div>`}).join('');
document.querySelector('#dailyRows').innerHTML=days.map((d,i)=>{let n=Math.round(volumes[i]/35),dif=available[i]-n,pct=Math.round(available[i]/n*100);return `<tr><td><b>${d}</b></td><td>${volumes[i].toLocaleString('de-CH')}</td><td>${n} FTE</td><td>${available[i]} FTE</td><td class="${dif<0?'amber':'green'}">${dif>0?'+':''}${dif} FTE</td><td><b>${pct}%</b></td><td><span class="pill ${pct>=95?'ok':'warn'}">${pct>=95?'Gedeckt':'Handlungsbedarf'}</span></td></tr>`}).join('');
document.querySelector('#planner').innerHTML=branches.map((b,i)=>`<article class="panel branchcard"><h3>${b.name}</h3><div class="inputs"><label>Forecast<input data-i="${i}" data-k="forecast" type="number" value="${b.forecast}"></label><label>Pakete / Stunde<input data-i="${i}" data-k="pph" type="number" step="0.1" value="${b.pph}"></label><label>Stunden auf Tour<input data-i="${i}" data-k="hours" type="number" value="${b.hours}"></label><label>Pakete / Fahrzeug<input data-i="${i}" data-k="ppv" type="number" value="${b.ppv}"></label><label>Absenzquote %<input data-i="${i}" data-k="absence" type="number" step="0.1" value="${b.absence}"></label><label>Verfügbar<input data-i="${i}" data-k="staff" type="number" value="${b.staff}"></label></div><div class="result"><span><b>${need(b)}</b><small>Fahrer benötigt</small></span><span><b>${vehicles(b)}</b><small>Fahrzeuge benötigt</small></span><span><b>${Math.max(0,need(b)-b.staff)}</b><small>Offene FTE</small></span></div></article>`).join('');
document.querySelectorAll('.planner input').forEach(el=>el.onchange=e=>{branches[e.target.dataset.i][e.target.dataset.k]=Number(e.target.value);render();toast('Planung neu berechnet')});
const hs=[['Zürich Nord',43.6,44],['Bern',45.2,44],['Basel',42.8,44],['Luzern',40.9,44]];document.querySelector('#hoursGrid').innerHTML=hs.map(h=>`<div class="hourrow"><b>${h[0]}</b><div class="hourtrack"><i style="width:${Math.min(100,h[1]/50*100)}%"></i></div><b>${h[1].toFixed(1)} Std.</b><span class="pill ${Math.abs(h[1]-h[2])<1.5?'ok':'warn'}">${h[1]<42.5?'Unter Ziel':h[1]>45.5?'Über Ziel':'Im Ziel'}</span></div>`).join('')}
const titles={overview:['Guten Morgen, Marco','Hier ist deine Personalplanung für diese Woche.'],planning:['Tagesplanung','Bedarf und verfügbare Kapazität je Filiale.'],hours:['Wochenstunden','Auslastung im Vergleich zum Zielwert.'],data:['Daten & Import','Aktualisiere Forecast und Personaldaten.'],settings:['Einstellungen','Passe die Planungsgrundlagen an.']};function switchTab(id){document.querySelectorAll('.tab,.nav').forEach(x=>x.classList.remove('active'));document.querySelector(`#${id}`).classList.add('active');document.querySelector(`.nav[data-tab="${id}"]`).classList.add('active');[pageTitle.textContent,subtitle.textContent]=titles[id]}
document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>switchTab(x.dataset.tab));document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>switchTab(x.dataset.go));document.querySelectorAll('.upload input').forEach(x=>x.onchange=()=>toast(`${x.files[0]?.name||'Datei'} erfolgreich eingelesen`));document.querySelector('#export').onclick=()=>{const blob=new Blob(['Filiale,Forecast,Fahrer,Fahrzeuge\n'+branches.map(b=>`${b.name},${b.forecast},${need(b)},${vehicles(b)}`).join('\n')],{type:'text/csv'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fleetly-personalbedarf.csv';a.click();toast('Bericht wurde exportiert')};document.querySelector('#saveSettings').onclick=()=>{localStorage.holiday=holiday.value;render();toast('Einstellungen gespeichert')};document.querySelector('#addBranch').onclick=()=>{branches.push({name:'Neue Filiale',forecast:1000,pph:22,hours:8,ppv:140,absence:5,staff:6});render()};function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}render();
